### ISSUE TITLE
boutiques features to add pre-paper (ideally)

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques-paper#7]
## features
- [x] resource requirements (cpu, ram) (https://github.com/boutiques/boutiques/issues/63)
- [x] entrypoint support 
- [x] docker directory mounting (https://github.com/boutiques/boutiques/issues/96)
- [ ] clean examples (https://github.com/boutiques/boutiques/issues/142)
- [x] bosh support for invocation schemas (https://github.com/boutiques/boutiques/issues/141)
- [ ] workflows: 
     - [x] spark workflows (spark BIDS)
     - [x] MOTEUR workflows (incl MICCAI challenge) @camarasu 
     - [x] describe CBRAIN sub-tasking (PSOM) 
     - [x] example of a Nipype workflow using boutiques (@ValHayot)
- [x] tests: just focus on coverage. 
- [x] API (https://github.com/boutiques/boutiques/issues/150) and documentation.
- [x] publisher to neurolinks
- [x] publish more tools to neurolinks

## extra features
- [ ] complex object commandlines for SPM (https://github.com/boutiques/boutiques/issues/101, https://github.com/boutiques/boutiques/issues/64)
- [ ] brep, a distributed Boutiques repository.

## possible additional descriptors or platforms
- [ ] nitrc tools (https://github.com/boutiques/boutiques/issues/48)
- [ ] nipype tools (https://github.com/boutiques/boutiques/issues/47)
- [ ] integration in SPINE
